version: "3.8"
services:
  server:
    container_name: "goChatServer"
    build:
      context: ./server
      dockerfile: DockerfileProd
    restart: unless-stopped

  client:
    container_name: "goChatClient"
    build:
      context: ./client
      dockerfile: DockerfileProd
    depends_on:
      - server
    restart: unless-stopped
